# Generated by Django 4.1.2 on 2023-03-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0003_rename_email_signupdetails_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='admin_email',
            field=models.CharField(max_length=100),
        ),
    ]
