# Generated by Django 4.1.2 on 2023-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0004_alter_signupdetails_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetails',
            name='admin_password',
            field=models.CharField(max_length=400),
        ),
    ]
