# Generated by Django 4.1.2 on 2023-03-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
