# Generated by Django 4.1.2 on 2023-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_alter_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
